apiVersion: v1
kind: Namespace
metadata:
  name: storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
  namespace: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-service
  template:
    metadata:
      labels:
        app: storage-service
    spec:
      containers:
        - name: storage-service
          image: marammanai/storage-service:latest
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: storage-service
  namespace: storage
spec:
  type: NodePort
  selector:
    app: storage-service
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30033
