spring.application.name=storage-service

# Base de données MySQL (injectée par variables d?environnement)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8090
server.servlet.context-path=/api/storage
server.error.include-message=always

# Ceph S3 (injecté par variables d?environnement)
ceph.s3.endpoint=${CEPH_S3_ENDPOINT}
ceph.s3.accessKey=${CEPH_S3_ACCESSKEY}
ceph.s3.secretKey=${CEPH_S3_SECRETKEY}
ceph.s3.bucket=${CEPH_S3_BUCKET}
ceph.s3.region=${CEPH_S3_REGION}

# Eureka
eureka.client.service-url.defaultZone=http://discovery-service.discovery.svc.cluster.local:8761/eureka/
eureka.instance.prefer-ip-address=true
