spring.application.name=storage-service

# Base de donnees MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8090
#server.servlet.context-path=/api/storage
server.error.include-message=always
jwt.secret=${JWT_SECRET}

# Ceph S3
ceph.s3.endpoint=${CEPH_S3_ENDPOINT}
ceph.s3.accessKey=${CEPH_S3_ACCESSKEY}
ceph.s3.secretKey=${CEPH_S3_SECRETKEY}
ceph.s3.bucket=${CEPH_S3_BUCKET}
ceph.s3.region=${CEPH_S3_REGION}

# Desactivation de Eureka pour eviter les erreurs
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
