spring.datasource.url=jdbc:mysql://localhost:3306/ceph_storage_service
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


server.port=8090
server.servlet.context-path=/api/storage
server.error.include-message=always

# Ceph S3
ceph.s3.endpoint=${CEPH_S3_ENDPOINT}
ceph.s3.accessKey=${CEPH_S3_ACCESSKEY}
ceph.s3.secretKey=${CEPH_S3_SECRETKEY}
ceph.s3.bucket=${CEPH_S3_BUCKET}
ceph.s3.region=${CEPH_S3_REGION}

# Desactivation de Eureka pour eviter les erreurs
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false